import { useState, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Swiper, SwiperSlide } from "swiper/react";
import {
  Autoplay,
  FreeMode,
  Navigation,
  Pagination,
  Thumbs,
  EffectCoverflow,
} from "swiper";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import useWindowSize from "@/Components/ScreenSize";
import styles from "@/styles/Home.module.css";
import art1 from "../photos/1.jpg";
import art2 from "../photos/2.jpg";
import art3 from "../photos/3.jpg";
import art4 from "../photos/4.jpg";
import art5 from "../photos/5.jpg";
import art6 from "../photos/6.jpg";
import art7 from "../photos/7.jpg";
import art8 from "../photos/8.jpg";
import art9 from "../photos/9.webp";
import art10 from "../photos/10.jpg";
import art11 from "../photos/11.jpg";
import art12 from "../photos/12.jpg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const windowSize = useWindowSize();
  const [thumbsSwiper, setThumbsSwiper] = useState(null);
  const progressCircle = useRef(null);
  const progressContent = useRef(null);
  const onAutoplayTimeLeft = (s, time, progress) => {
    progressCircle.current.style.setProperty("--progress", 1 - progress);
    progressContent.current.textContent = `${Math.ceil(time / 1000)}s`;
  };

  return (
    <>
      <Head>
        <title>artSam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.row_1}>
          <div className={styles.row_1_background_screen}></div>
          <div className={styles.row_1_content}>
            Capture the beauty of nature in a hand-painted work of art created
            just for you.
          </div>
        </div>

        <hr size="5" width="100%" color="white" />

        <div className={styles.row_2}>
          “ The object of art is not to reproduce reality, but to create a
          reality of the same intensity. ”
        </div>

        <hr size="5" width="100%" color="white" />

        <div className={styles.row_3}>
          <button className={styles.order_drawing_button}>Order_Now</button>
          <div
            className={styles.photos_container}
            style={{
              height:
                windowSize.height - 100 > windowSize.width
                  ? windowSize.width
                  : windowSize.height - 100,
            }}
          >
            {
              <Swiper
                effect={"coverflow"}
                grabCursor={true}
                centeredSlides={true}
                coverflowEffect={{
                  rotate: 50,
                  stretch: 0,
                  depth: 100,
                  modifier: 1,
                  slideShadows: true,
                }}
                loop={true}
                spaceBetween={10}
                navigation={true}
                slidesPerView={"auto"}
                freeMode={true}
                pagination={{
                  clickable: true,
                }}
                thumbs={{ swiper: thumbsSwiper }}
                modules={[
                  Autoplay,
                  FreeMode,
                  Navigation,
                  Pagination,
                  EffectCoverflow,
                ]}
                autoplay={{
                  delay: 6000,
                  disableOnInteraction: false,
                }}
                onAutoplayTimeLeft={onAutoplayTimeLeft}
                className="mySwiper"
              >
                <SwiperSlide className="swiper-slide">
                  <Image src={art1} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art2} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art3} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art4} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art5} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art6} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art7} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art8} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art9} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art10} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art11} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <SwiperSlide>
                  <Image src={art12} alt="art 1" className={styles.photos} />
                </SwiperSlide>
                <div className="autoplay-progress" slot="container-end">
                  <svg viewBox="0 0 48 48" ref={progressCircle}>
                    <circle cx="24" cy="24" r="20"></circle>
                  </svg>
                  <span ref={progressContent}></span>
                </div>
              </Swiper>
            }
          </div>
        </div>

        <hr size="5" width="100%" color="white" />
        <div className={styles.row_4}>
          <div className={styles.row_4_header}>
            Trending Artists on Karadolo Arts
          </div>
          <Image src={art5} alt="" className={styles.trending_artist} />
        </div>
        <hr size="5" width="100%" color="white" />
      </div>
    </>
  );
}
